#
- name: build the service
  hosts: controller1.lab.example.com
  become: yes
  gather_facts: no
  tasks: 

# network manager

# firewall
  - name: permit traffic in default zone
    ansible.posix.firewalld:
      service: dns
      immediate: yes
      permanent: yes
      state: enabled
#
# checks

# packages
