# incomplete
- name: build the control node
  hosts: control1.lab.example.com
  become: yes
  gather_facts: no
  tasks: 

# network manager

# firewall
# https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_installation_guide/index#ref-access-control-requirements_planning
  - name: permit traffic in default zone
    ansible.posix.firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    loop:
      - ssh
      - http
      - https
#
# checks

# packages



- name: build the execution node
  hosts: execution1.lab.example.com
  become: yes
  gather_facts: no
  tasks: 

# network manager

# firewall
# https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_installation_guide/index#ref-access-control-requirements_planning
  - name: permit traffic in default zone
    ansible.posix.firewalld:
      port: 27199/tcp
      immediate: yes
      permanent: yes
      state: enabled
#
# checks

# packages



- name: build the hub node
  hosts: hub1.lab.example.com
  become: yes
  gather_facts: no
  tasks: 

# network manager

# firewall
# https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_installation_guide/index#ref-access-control-requirements_planning
  - name: permit traffic in default zone
    ansible.posix.firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    loop:
      - ssh
      - http
      - https
#
# checks

# packages
