---
- name: build new machine
  hosts: all
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - role: libvirt-guest
    delegate_to: localhost
    connection: local

- name: check new machine
  hosts: all
  become: no
  gather_facts: no
  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30

