# Probably a good idea to use these for install.
# 1. https://github.com/redhat-cop/aap_utilities/tree/devel/roles/aap_setup_download
# 2. https://github.com/redhat-cop/aap_utilities/tree/devel/roles/aap_setup_prepare
# 3. https://github.com/redhat-cop/aap_utilities/tree/devel/roles/aap_setup_install
# Then use these for config. 
# 4. https://github.com/redhat-cop/controller_configuration
# 5. https://github.com/redhat-cop/ah_configuration

- name: service builld
  hosts: hub1.lab.example.com
  become: yes
  gather_facts: no
  tasks: 


  # setup.sh wants hub cert and key on the controller
  # !!! delete after install
  - name: fetch cert from hub to controller /etc/pki/tls/certs/
    ansible.builtin.fetch:
      src: "/etc/pki/tls/certs/hub1.lab.example.com.pem"
      dest: "/var/tmp/"
      flat: yes

  - name: fetch key from hub to controller 
    ansible.builtin.fetch:
      src: "/etc/pki/tls/private/hub1.lab.example.com.key"
      dest: "/var/tmp/"
      flat: yes

# install process
# https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html-single/red_hat_ansible_automation_platform_installation_guide/index
# dnf install --enablerepo=ansible-automation-platform-2.2-for-rhel-9-x86_64-rpm ansible-automation-platform-installer
# subscription-manager repos --enable ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms
# install from control1
# control1
# copy setup files to /opt/ansible-automation-platform/installer/
# dnf install ansible-automation-platform-installer
#
# create root keys - ssh-keygen
# copy id_rsa.pub to .ssh/authorized keys
# hub1
# execution1
# root access to the other machines
# copy id_rsa.pub to .ssh/authorized keys
# control1
# check access, auth, DNS
# ssh control1.lab.example.com
# ssh hub1.lab.example.com
# ssh execution1.lab.example.com
# cd /opt/ansible-automation-platform/installer/
# copy inventory 
# change registry_username and registry_password in inventory
# check registry account - podman login registry.redhat.io
# ./setup.sh
# get a subscription manifest
# https://access.redhat.com/documentation/en-us/reference_architectures/2021/html-single/deploying_ansible_automation_platform_2.1/index#sub_manifest
#
